apiVersion: v1
kind: Pod
metadata:
  name: advertising
  labels:
    name: advertising
spec:
  containers:
    - image: tads2015da/demo-advertising:0.0.5
      name: advertising
      env:
        - name: EXTERNAL_IP
          value: 172.31.35.179
        - name: RESTCOMM_SERVICE
          value: 52.6.201.57:8080
      ports:
        - containerPort: 30792
        - containerPort: 30793
