apiVersion: v1
kind: Pod
metadata:
  name: advertising
  labels:
    name: advertising
spec:
  containers:
    - image: tads2015da/demo-advertising:0.0.9
      name: advertising
      env:
        - name: EXTERNAL_IP
          value: EXTERNAL_IP_VALUE
        - name: RESTCOMM_SERVICE
          value: RESTCOMM_SERVICE_VALUE
      ports:
        - containerPort: 30792
        - containerPort: 30793
