apiVersion: v1
kind: ReplicationController
metadata:
  name: advertising
  labels:
    name: advertising
spec:
  replicas: 1
  selector:
    name: advertising
  template:
    metadata:
      labels:
        name: advertising
    spec:
      containers:
      - name: advertising
        image: taddemo/advertising:0.0.1
        env:
        - name: EXTERNAL_IP
          value: 192.168.176.220
        - name: RESTCOMM_SERVICE
          value: 52.0.167.47:8080
        ports:
        - containerPort: 30792
        - containerPort: 30793
