apiVersion: v1
kind: ReplicationController
metadata:
  name: conference
  labels:
    name: conference
spec:
  replicas: 1
  selector:
    name: conference
  template:
    metadata:
      labels:
        name: conference
    spec:
      containers:
      - name: main
        image: tads2015da/demo-conference:0.0.9
        env:
        - name: EXTERNAL_IP
          value: EXTERNAL_IP_VALUE
        - name: RESTCOMM_SERVICE
          value: RESTCOMM_SERVICE_VALUE
        ports:
        - containerPort: 30791
