apiVersion: v1
kind: ReplicationController
metadata:
  name: main
  labels:
    name: main
spec:
  replicas: 1
  selector:
    name: main
  template:
    metadata:
      labels:
        name: main
    spec:
      containers:
      - name: main
        image: taddemo/main:0.0.1
        env:
        - name: EXTERNAL_IP
          value: 192.168.176.220
        - name: RESTCOMM_SERVICE
          value: 52.0.167.47:8080
        ports:
        - containerPort: 30790
