apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    name: main
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 30790
    targetPort: 30790
  selector:
    name: main
