apiVersion: v1
kind: ReplicationController
metadata:
  name: main
  labels:
    name: main
spec:
  replicas: 1
  selector:
    name: main
  template:
    metadata:
      labels:
        name: main
    spec:
      containers:
      - name: main
        image: tads2015da/demo-main:0.0.5
        env:
        - name: EXTERNAL_IP
          value: 172.31.35.179
        - name: RESTCOMM_SERVICE
          value: 52.6.201.57:8080
        ports:
        - containerPort: 30790
