apiVersion: v1
kind: ReplicationController
metadata:
  name: main
  labels:
    name: main
spec:
  replicas: 1
  selector:
    name: main
  template:
    metadata:
      labels:
        name: main
    spec:
      containers:
      - name: main
        image: tads2015da/demo-main:0.0.9
        env:
        - name: EXTERNAL_IP
          value: EXTERNAL_IP_VALUE
        - name: RESTCOMM_SERVICE
          value: RESTCOMM_SERVICE_VALUE
        - name: REDIS_SERVICE_HOST
          value: REDIS_SERVICE_HOST_VALUE
        - name: REDIS_SERVICE_PORT
          value: REDIS_SERVICE_PORT_VALUE
        ports:
        - containerPort: 30790
