apiVersion: v1
kind: Pod
metadata:
  name: feedback
  labels:
    name: feedback
spec:
  containers:
    - image: tads2015da/demo-advertising:0.0.9
      name: feedback
      env:
        - name: EXTERNAL_IP
          value: EXTERNAL_IP_VALUE
        - name: RESTCOMM_SERVICE
          value: RESTCOMM_SERVICE_VALUE
        - name: REDIS_SERVICE_HOST
          value: REDIS_SERVICE_HOST_VALUE
        - name: REDIS_SERVICE_PORT
          value: 'REDIS_SERVICE_PORT_VALUE'
      ports:
        - containerPort: 30792
        - containerPort: 30793
