apiVersion: v1
kind: Pod
metadata:
  name: advertising
  labels:
    name: advertising
spec:
  containers:
    - image: tads2015da/demo-advertising:0.0.5
      name: advertising
      env:
        - name: EXTERNAL_IP
          value: ac7df193a45c911e5b7b11260ed06e85-959026579.us-east-1.elb.amazonaws.com
        - name: RESTCOMM_SERVICE
          value: 192.168.176.220:7070
      ports:
        - containerPort: 30792
        - containerPort: 30793
